name: MSYS2
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - develop
jobs:
  msys2-mingw:
    name: Publish for Windows 64
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: oprypin/find-latest-tag@v1
        id: gettag
        with:
          repository: PerryWerneck/udjat-module-sqlite
          releases-only: true
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: dos2unix xz mingw-w64-x86_64-gcc automake autoconf make git pkgconf mingw-w64-x86_64-gettext gettext-devel libtool mingw-w64-x86_64-pugixml
      - uses: robinraju/release-downloader@v1.7
        with:
          repository: "PerryWerneck/vmdetect"
          latest: true
          fileName: "mingw-w64-x86_64-vmdetect-1.1-1-x86_64.pkg.tar.zst"
      - uses: robinraju/release-downloader@v1.7
        with:
          repository: "PerryWerneck/libudjat"
          latest: true
          fileName: "mingw-w64-x86_64-libudjat-1.1-1-x86_64.pkg.tar.zst"
      - name: CI-Build
        run: ./win/ci-build.sh
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.gettag.outputs.tag }}
          artifacts: "*-users-*.pkg.tar.zst"
          allowUpdates: true
          draft: false
          makeLatest: true
          omitBody: true
          omitPrereleaseDuringUpdate: true
          replacesArtifacts: true

